//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCargos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCargos()
        {
            this.tbEmpleado = new HashSet<tbEmpleado>();
        }
    
        public int Carg_Id { get; set; }
        public string Carg_Descripcion { get; set; }
        public Nullable<int> Carg_Usuario_Creacion { get; set; }
        public Nullable<System.DateTime> Carg_Fecha_Creacion { get; set; }
        public Nullable<int> Carg_Usuario_Modificacion { get; set; }
        public Nullable<System.DateTime> Carg_Fecha_Modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEmpleado> tbEmpleado { get; set; }
    }
}
