//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFacturas_Encabezados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFacturas_Encabezados()
        {
            this.tbFacturas_Detalles = new HashSet<tbFacturas_Detalles>();
        }
    
        public int Fact_Id { get; set; }
        public Nullable<System.DateTime> Fact_Fecha { get; set; }
        public Nullable<int> Clie_Id { get; set; }
        public Nullable<int> Empl_Id { get; set; }
        public Nullable<int> Tipo_Id { get; set; }
        public Nullable<int> Fact_Usua_Creacion { get; set; }
        public Nullable<System.DateTime> Fact_Fecha_Creacion { get; set; }
        public Nullable<int> Fact_Usua_Modifica { get; set; }
        public Nullable<System.DateTime> Fact_Fecha_Modifica { get; set; }
        public Nullable<bool> Fact_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFacturas_Detalles> tbFacturas_Detalles { get; set; }
        public virtual tbClientes tbClientes { get; set; }
        public virtual tbEmpleado tbEmpleado { get; set; }
        public virtual tbTipo_Pagos tbTipo_Pagos { get; set; }
    }
}
