//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPantalla_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPantalla_Roles()
        {
            this.tbUsuario = new HashSet<tbUsuario>();
        }
    
        public int Paro_Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> Pant_Id { get; set; }
    
        public virtual tbPantallas tbPantallas { get; set; }
        public virtual tbRoles tbRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuario> tbUsuario { get; set; }
    }
}
