//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSalas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSalas()
        {
            this.tbEntradas = new HashSet<tbEntradas>();
        }
    
        public int Sala_Id { get; set; }
        public string Sala_Descripcion { get; set; }
        public Nullable<int> Buta_Id { get; set; }
        public Nullable<int> Cate_Usuario_Creacion { get; set; }
        public Nullable<System.DateTime> Cate_Fecha_Creacion { get; set; }
        public Nullable<int> Cate_Usuario_Modificacion { get; set; }
        public Nullable<System.DateTime> Cate_Fecha_Modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEntradas> tbEntradas { get; set; }
        public virtual tbButacas_Salas tbButacas_Salas { get; set; }
    }
}
