//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbButacas_Salas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbButacas_Salas()
        {
            this.tbSalas = new HashSet<tbSalas>();
        }
    
        public int Buta_Id { get; set; }
        public string Buta_Descripcion { get; set; }
        public Nullable<int> Buta_Usuario_Creacion { get; set; }
        public Nullable<System.DateTime> Buta_Fecha_Creacion { get; set; }
        public Nullable<int> Buta_Usuario_Modificacion { get; set; }
        public Nullable<System.DateTime> Buta_Fecha_Modificacion { get; set; }
        public Nullable<bool> Buta_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSalas> tbSalas { get; set; }
    }
}
