//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCarteleras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCarteleras()
        {
            this.tbFacturas_Detalles = new HashSet<tbFacturas_Detalles>();
            this.tbSucursales = new HashSet<tbSucursales>();
        }
    
        public int Cart_Id { get; set; }
        public string Cart_Descripcion { get; set; }
        public Nullable<int> Gene_Id { get; set; }
        public Nullable<int> Prom_Id { get; set; }
        public Nullable<int> Entra_Id { get; set; }
        public Nullable<int> Cart_Fecha_Estreno { get; set; }
        public Nullable<int> Cart_Usuario_Creacion { get; set; }
        public Nullable<System.DateTime> Cart_Fecha_Creacion { get; set; }
        public Nullable<int> Cart_Usuario_Modificacion { get; set; }
        public Nullable<System.DateTime> Cart_Fecha_Modificacion { get; set; }
        public Nullable<bool> Cart_Estado { get; set; }
    
        public virtual tbEntradas tbEntradas { get; set; }
        public virtual tbGeneros tbGeneros { get; set; }
        public virtual tbPromociones tbPromociones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFacturas_Detalles> tbFacturas_Detalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSucursales> tbSucursales { get; set; }
    }
}
