//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbClientes()
        {
            this.tbFacturas_Encabezados = new HashSet<tbFacturas_Encabezados>();
        }
    
        public int Clie_Id { get; set; }
        public string Clie_Nombre { get; set; }
        public string Clie_Apellido { get; set; }
        public string Clie_Identidad { get; set; }
        public string Clie_Sexo { get; set; }
        public Nullable<int> Clie_Telefono { get; set; }
        public Nullable<int> Esta_Id { get; set; }
        public Nullable<System.DateTime> Clie_FecNacimiento { get; set; }
        public string Muni_Id { get; set; }
        public Nullable<int> Clie_Usua_Creacion { get; set; }
        public Nullable<System.DateTime> Clie_Fecha_Creacion { get; set; }
        public Nullable<int> Clie_Usua_Modifica { get; set; }
        public Nullable<System.DateTime> Clie_Fecha_Modifica { get; set; }
        public Nullable<bool> Clie_Estado { get; set; }
    
        public virtual tbEstado_Civil tbEstado_Civil { get; set; }
        public virtual tbMunicipio tbMunicipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFacturas_Encabezados> tbFacturas_Encabezados { get; set; }
    }
}
