//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEntradas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEntradas()
        {
            this.tbCarteleras = new HashSet<tbCarteleras>();
            this.tbSucursales = new HashSet<tbSucursales>();
        }
    
        public int Entra_Id { get; set; }
        public Nullable<int> Entra_Cantidad { get; set; }
        public Nullable<int> Sala_Id { get; set; }
        public Nullable<int> Entra_Usuario_Creacion { get; set; }
        public Nullable<System.DateTime> Entra_Fecha_Creacion { get; set; }
        public Nullable<int> Entra_Usuario_Modificacion { get; set; }
        public Nullable<System.DateTime> Entra_Fecha_Modificacion { get; set; }
        public Nullable<bool> Entra_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCarteleras> tbCarteleras { get; set; }
        public virtual tbSalas tbSalas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSucursales> tbSucursales { get; set; }
    }
}
