//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFacturas_Detalles
    {
        public int Fade_Id { get; set; }
        public Nullable<int> Fact_Id { get; set; }
        public Nullable<int> Cart_Id { get; set; }
        public Nullable<int> Fade_ticket { get; set; }
        public Nullable<int> Fade_Usua_Creacion { get; set; }
        public Nullable<System.DateTime> Fade_Fecha_Creacion { get; set; }
        public Nullable<int> Fade_Usua_Modifica { get; set; }
        public Nullable<System.DateTime> Fade_Fecha_Modificacion { get; set; }
        public Nullable<bool> Fade_Estado { get; set; }
    
        public virtual tbCarteleras tbCarteleras { get; set; }
        public virtual tbFacturas_Encabezados tbFacturas_Encabezados { get; set; }
    }
}
