//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGeneros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbGeneros()
        {
            this.tbCarteleras = new HashSet<tbCarteleras>();
        }
    
        public int Gene_Id { get; set; }
        public string Gene_Descripcion { get; set; }
        public Nullable<int> Prom_Id { get; set; }
        public Nullable<int> Gene_Usuario_Creacion { get; set; }
        public Nullable<System.DateTime> Gene_Fecha_Creacion { get; set; }
        public Nullable<int> Gene_Usuario_Modificacion { get; set; }
        public Nullable<System.DateTime> Gene_Fecha_Modificacion { get; set; }
        public Nullable<bool> Gene_Estado { get; set; }
    
        public virtual tbPromociones tbPromociones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCarteleras> tbCarteleras { get; set; }
    }
}
