//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPantalla_Roles
    {
        public int Paro_Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> Pant_Id { get; set; }
        public Nullable<int> Pant_Creacion { get; set; }
        public Nullable<System.DateTime> Pant_Fecha_Creacion { get; set; }
        public Nullable<int> Pant_Modifica { get; set; }
        public Nullable<System.DateTime> Pant_Fecha_Modifica { get; set; }
        public Nullable<bool> Pant_Estado { get; set; }
    
        public virtual tbRoles tbRoles { get; set; }
        public virtual tbPantallas tbPantallas { get; set; }
    }
}
