//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Cine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbRoles()
        {
            this.tbPantalla_Roles = new HashSet<tbPantalla_Roles>();
            this.tbUsuarios = new HashSet<tbUsuarios>();
        }
    
        public int Role_Id { get; set; }
        public string Role_Descripcion { get; set; }
        public Nullable<int> Role_Creacion { get; set; }
        public Nullable<System.DateTime> Role_Fecha_Creacion { get; set; }
        public Nullable<int> Role_Modifica { get; set; }
        public Nullable<System.DateTime> Role_Fecha_Modifica { get; set; }
        public Nullable<bool> Role_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPantalla_Roles> tbPantalla_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}
